import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" />
      </head>
      <body>
        <header>
          <img src="/Images/My-removebg-preview.png" alt="Logo" className="logo" />
        </header>
        <hr />
        {children}
        <footer>
          <p>&copy; 2022 MYCSE Portal Computer Science and Engineering Department | Contact: support@qu.edu.qa</p>
        </footer>
      </body>
    </html>
  );
}
